# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0017c0bacb8810a2fc257076d9d5ef5c1cf4ff1d1929390c4a19f04f5c5c7f0fba5bc2022aa2339a91fc62543b434aaf2292e55cc1f4585a9a83bd9af8d20b26

test:
  secret_key_base: 2abbc2a8248fa9cfd2202cbfc366a45495ee568c5d9e62edeafb0b2c15c44d9cbbe70b0d4da8df93ed78748945a36a3cb5d9addb89e20fbab5fd3472257fa4a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
